"use client";

import { AlertTriangle, TrendingDown, DollarSign } from "lucide-react";

export default function ProblemSection() {
  return (
    <div id="problem" className="w-full">
      {/* PROBLEM PART 1: THE BIG NUMBERS (Maximal Whitespace & Huge Numerals) */}
      <section className="py-32 sm:py-40 px-6 sm:px-8 max-w-7xl mx-auto hairline-t">
        <div className="text-center max-w-3xl mx-auto space-y-4 mb-20">
          <p className="text-xs font-mono uppercase tracking-widest text-accent">
            The Kirana Scale
          </p>
          <h2 className="text-3xl sm:text-5xl font-display font-extrabold text-text-primary tracking-tight">
            India runs on 13 Million neighborhood stores.
          </h2>
        </div>

        {/* 3 Massive Number Focal Points */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-12 sm:gap-16 text-center">
          
          <div className="space-y-4 p-8 rounded-2xl bg-surface hairline-all">
            <h3 className="text-6xl sm:text-7xl font-display font-black text-accent tracking-tight">
              13M+
            </h3>
            <p className="text-sm text-text-secondary leading-relaxed max-w-xs mx-auto">
              Kirana stores power India&apos;s daily commerce, serving every urban neighborhood and rural village.
            </p>
          </div>

          <div className="space-y-4 p-8 rounded-2xl bg-surface hairline-all">
            <h3 className="text-6xl sm:text-7xl font-display font-black text-accent tracking-tight">
              ~90%
            </h3>
            <p className="text-sm text-text-secondary leading-relaxed max-w-xs mx-auto">
              Of all Fast-Moving Consumer Goods (FMCG) sales across the nation flow through Kirana counters.
            </p>
          </div>

          <div className="space-y-4 p-8 rounded-2xl bg-surface hairline-all">
            <h3 className="text-6xl sm:text-7xl font-display font-black text-accent tracking-tight">
              ~11%
            </h3>
            <p className="text-sm text-text-secondary leading-relaxed max-w-xs mx-auto">
              Of India&apos;s total Gross Domestic Product (GDP) is generated by this single retail backbone.
            </p>
          </div>

        </div>
      </section>

      {/* PROBLEM PART 2: THE NARRATIVE & PAIN POINTS (Distinct Calm Scroll Moment) */}
      <section className="py-32 sm:py-40 px-6 sm:px-8 max-w-7xl mx-auto hairline-t">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start">
          
          {/* Left Split Heading */}
          <div className="lg:col-span-5 space-y-6">
            <p className="text-xs font-mono uppercase tracking-widest text-accent">
              The Operational Crisis
            </p>
            <h2 className="text-3xl sm:text-5xl font-display font-extrabold text-text-primary tracking-tight leading-tight">
              30-year-old manual methods are quietly bleeding profits.
            </h2>
            <p className="text-text-secondary text-base leading-relaxed">
              Despite driving a trillion-dollar commerce engine, single-owner Kiranas operate without barcode scanners or expensive enterprise POS terminals. Visual estimation leads to recurring inventory disasters.
            </p>
          </div>

          {/* Right Cards: The Core Frictions */}
          <div className="lg:col-span-7 space-y-6">
            
            <div className="p-8 rounded-2xl bg-surface hairline-all space-y-3">
              <div className="flex items-center gap-3">
                <DollarSign className="w-5 h-5 text-accent" />
                <h3 className="text-xl font-display font-bold text-text-primary">
                  Overstock Capital Lockup &amp; Spoilage
                </h3>
              </div>
              <p className="text-sm text-text-secondary leading-relaxed pl-8">
                Over-ordering locks up vital working capital in slow-moving perishables. Expired goods rot on backroom shelves, destroying slim Kirana profit margins.
              </p>
            </div>

            <div className="p-8 rounded-2xl bg-surface hairline-all space-y-3">
              <div className="flex items-center gap-3">
                <TrendingDown className="w-5 h-5 text-accent" />
                <h3 className="text-xl font-display font-bold text-text-primary">
                  Understock &amp; Customer Defection
                </h3>
              </div>
              <p className="text-sm text-text-secondary leading-relaxed pl-8">
                Running out of staples like Maggi or Amul Milk sends loyal neighborhood customers directly to competing Kiranas next door. Lost sales are never recovered.
              </p>
            </div>

            <div className="p-8 rounded-2xl bg-surface hairline-all space-y-3">
              <div className="flex items-center gap-3">
                <AlertTriangle className="w-5 h-5 text-accent" />
                <h3 className="text-xl font-display font-bold text-text-primary">
                  No Tool Built for Single-Owner Scale
                </h3>
              </div>
              <p className="text-sm text-text-secondary leading-relaxed pl-8">
                Enterprise software demands handheld barcode guns, monthly SaaS subscriptions, and manual SKU entry—completely unsuited for busy sole shopkeepers.
              </p>
            </div>

          </div>

        </div>
      </section>
    </div>
  );
}
