"use client";

import { CheckCheck, MessageSquare, Send } from "lucide-react";
import WhatsAppBubble from "@/src/components/WhatsAppBubble";

export default function AlertsFeed() {
  return (
    <div className="w-full bg-surface rounded-2xl hairline-all p-6 space-y-6">
      <div className="flex items-center justify-between border-b border-white/10 pb-4">
        <div>
          <h2 className="text-lg font-display font-bold text-text-primary">
            Automated WhatsApp Reorder Feed
          </h2>
          <p className="text-xs text-text-secondary">
            Proactive supplier draft alerts generated by StockSaathi Decision Engine.
          </p>
        </div>
        <div className="flex items-center gap-1.5 px-3 py-1 rounded-full bg-[#25D366]/10 text-[#25D366] text-xs font-mono border border-[#25D366]/20">
          <MessageSquare className="w-3.5 h-3.5" />
          <span>WhatsApp API Connected</span>
        </div>
      </div>

      {/* Feed List */}
      <div className="space-y-6">
        
        {/* Alert 1 */}
        <div className="p-4 rounded-xl bg-surface-2 hairline-all space-y-4">
          <div className="flex items-center justify-between text-xs font-mono text-text-secondary">
            <span className="text-accent font-bold">ALERT #WA-9042 • CRITICAL</span>
            <span>Today, 10:42 AM</span>
          </div>

          <WhatsAppBubble
            storeName="Gupta Kirana Store"
            supplierName="Mahalakshmi Wholesale FMCG"
            items={[
              { name: "Maggi 70g Masala Noodles", qty: "48 pkts (2 crates)", alertType: "CRITICAL" },
              { name: "Fortune Sunlite Oil 1L", qty: "15 tins (1 carton)", alertType: "CRITICAL" },
            ]}
            timestamp="10:42 AM"
            status="sent"
          />

          <div className="flex items-center justify-between pt-2">
            <span className="text-xs text-emerald-400 font-mono flex items-center gap-1">
              <CheckCheck className="w-4 h-4" /> Order Approved by Shopkeeper
            </span>
            <button className="px-3 py-1.5 rounded-lg bg-[#25D366] text-black text-xs font-mono font-bold flex items-center gap-1.5 hover:bg-[#20bd5a] transition-colors">
              <Send className="w-3 h-3" /> Resend WhatsApp
            </button>
          </div>
        </div>

        {/* Alert 2 */}
        <div className="p-4 rounded-xl bg-surface-2 hairline-all space-y-4">
          <div className="flex items-center justify-between text-xs font-mono text-text-secondary">
            <span className="text-amber-400 font-bold">ALERT #WA-9041 • REORDER SOON</span>
            <span>Yesterday, 4:15 PM</span>
          </div>

          <WhatsAppBubble
            storeName="Gupta Kirana Store"
            supplierName="Amul Direct Distributors"
            items={[
              { name: "Parle-G 80g Biscuit", qty: "30 pkts (1 carton)", alertType: "LOW" },
              { name: "Colgate Strong Teeth 100g", qty: "12 tubes", alertType: "LOW" },
            ]}
            timestamp="4:15 PM"
            status="read"
          />

          <div className="flex items-center justify-between pt-2">
            <span className="text-xs text-text-secondary font-mono">
              Status: Delivered &amp; Confirmed
            </span>
            <span className="text-xs font-mono text-accent">
              Dispatched by Wholesaler
            </span>
          </div>
        </div>

      </div>
    </div>
  );
}
